### ISSUE TITLE
Array support?

### ISSUE THREAD

**Issue by sovcharenko** [dry-rb/dry-configurable#73]
I'm trying to declare a configuration with the following structure (in YAML notation)

```
...
endpoints:
  - url: "https://host1.domain.com"
    priority: 1
  - url: "https://host2.domain.com"
    priority: 2   
...

```

Am I missing something or it's not possible to declare a `setting` of an array type?

Something like this:

```
setting :endpoints do
  setting :url
  setting :priority
end
```
      

Thanks
